In [1]:
import  numpy as np

In [2]:
x = np.linspace(3,10,10)
print(x
     )

[ 3.          3.77777778  4.55555556  5.33333333  6.11111111  6.88888889
  7.66666667  8.44444444  9.22222222 10.        ]


In [5]:
x<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

In [7]:
x=np.linspace(1,10,20)

In [10]:
x**2<x+x

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [113]:
x=np.random.randint(50, size=(2,3,10))
x

array([[[47,  4, 22, 30, 23, 46, 10, 40, 18, 38],
        [42, 31,  0, 20, 24, 48, 43,  1, 42, 39],
        [ 9,  4,  7, 47, 41, 49, 21, 31, 46, 15]],

       [[23, 49, 16, 14, 46, 42, 14, 14,  5, 34],
        [35, 39, 12, 45, 15,  4, 37,  5,  4, 40],
        [15, 13, 44, 11,  8, 25, 13, 21, 42, 21]]])

In [126]:
x=np.zeros(20)[:np.newaxis]
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [175]:
x=np.arange(0,30,1).reshape(6,5)
print(x)
np.outer(x,x)
np.all(x>2,axis=0)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


array([False, False, False,  True,  True])

In [185]:
x=np.random.randint(20, size=(1,20))
y=(x>2)&(x<7)
y
x[y]

array([6, 5, 6, 6, 5, 4, 6])

In [200]:
x=np.linspace(1,10,10)
xv[[1,2,3]]


array([2., 3., 4.])

In [231]:
X=np.random.random(9).reshape(3,3)
row=np.array([0,1,2])
a=np.array([1,0,1], dtype=bool)
print(X)
b=a.reshape(1,3)
X[a[:,np.newaxis],a]

[[0.16645136 0.20283318 0.94010221]
 [0.26495501 0.8039424  0.40884726]
 [0.80434854 0.72035685 0.90388662]]


IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [235]:
a=np.random.randint(40,size=(1,3))
b=np.random.randint(40,size=(1,3))
np.concatenate(a,b
    )

TypeError: only integer scalar arrays can be converted to a scalar index